### PR TITLE
Migration to Svelte 5

### PR DESCRIPTION
**Pull request by david-palomo**
`sv migrate` did most of the work, and the minimal interface helped too.

### Changelog

* Updated dependencies
* Refactored components to use Svelte 5 syntax (`$props`,  `$state`,  `children`...)
* Added a .env.example file

PS: Thank you so much for this project, super useful stuff!

### CODE REVIEW

**Comment by j4w8n** [comment]
Thanks so much for this @david-palomo. Once you get a few of these things buttoned up, I'll merge.

**Comment by david-palomo** [comment]
Hey! I can't see if any request for changes was added for me to address. Are you expecting anything from my side?

**Comment by j4w8n** [comment]
Does your side show my review comments?

**Comment by david-palomo** [comment]
No, I see no reviews and no comments on the Files Changed tab. Did you submit your review?

**Review by j4w8n — CHANGES_REQUESTED** [review]

**Comment by j4w8n** [comment]
@david-palomo anything now? Apparently I just don't know what I'm doing 😆

**Comment by david-palomo** [comment]
Done! My linter/formatter applied changes on save, didn't mean to impose semicolons and such 😅

**Review by j4w8n — APPROVED** [review]

**Pull request merged**
